######################## default configuration ####################
baseURL = "https://www.alpharettalions.com"
title = "Alpharetta Lions Club"
theme = "alpharetta-lions"
themesDir = "../.."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
#disqusShortname = "educenter" # get your shortname form here : https://disqus.com


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Alpharetta Lions Club Home Page"
author = "Alpharetta Lions Club"
# contact info
address = "Alpharetta, GA"
mobile = ""
email = "info@alpharettalions.com"
# contact form action
contact_form_action = "https://formspree.io/f/xeqpbagr" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
#[params.map]
#enable = false
#gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
#map_latitude = "34.13197"
#map_longitude = "-84.26002"
#map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = false
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/AlpharettaLionsClub"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/AlpharettaLions"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/alpharettalions/"

#[[params.social]]
#title = "github"
#icon = "ti-github" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "https://www.linkedin.com/todo"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 Alpharetta Lions Club Foundation.  Hugo theme &copy; 2020 [themefisher](https://themefisher.com)"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "Join"
url = "join"
weight = 1

[[Languages.en.menu.main]]
name = "Golf"
url = "fundraiser/golf/"
weight = 2

[[Languages.en.menu.main]]
name = "Sponsors"
url = "fundraiser/golf/"
weight = 3


[[Languages.en.menu.main]]
weight = 4
name = "Happenings"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Happenings"
  weight = 1
  name = "Events"
  url = "event"

  [[Languages.en.menu.main]]
  parent = "Happenings"
  weight = 3
  name = "News"
  url = "news"
  
  [[Languages.en.menu.main]]
  parent = "Happenings"
  weight = 2
  name = "Fundraisers"
  url = "fundraiser"
  
  [[Languages.en.menu.main]]
  parent = "Happenings"
  weight = 4
  name = "Eyeglasses"
  url = "https://www.alpharettalions.com/eyeglasses/map.html"
  
[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 5

[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 6


# footer menu

[[Languages.en.menu.footer]]
name = "Lions Clubs International"
url = "https://www.lionsclubs.org"

[[Languages.en.menu.footer]]
name = "Georgia Lions Lighthouse"
url = "https://lionslighthouse.org/"

#[[Languages.en.menu.footer]]
#name = "event"
#url = "event"
#
#[[Languages.en.menu.footer]]
#name = "scholarship"
#url = "scholarship"
#
#[[Languages.en.menu.footer]]
#name = "research"
#url = "research"

